/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author SENA
 */
public class Agregar_Detalleproducto extends javax.swing.JFrame {

    /**
     * Creates new form Agregar_Producto
     */
    public Agregar_Detalleproducto() {
        initComponents();
    }

    public JPanel getJPanelAgregarProducto() {
        return JPanelAgregarProducto;
    }

    public void setJPanelAgregarProducto(JPanel JPanelAgregarProducto) {
        this.JPanelAgregarProducto = JPanelAgregarProducto;
    }

    public JTable getJTablaagragarproducto() {
        return JTablaagragarproducto;
    }

    public void setJTablaagragarproducto(JTable JTablaagragarproducto) {
        this.JTablaagragarproducto = JTablaagragarproducto;
    }
    
    public JButton getBtnagregar() {
        return btnagregar;
    }

    public void setBtnagregar(JButton btnagregar) {
        this.btnagregar = btnagregar;
    }

    public JTextField getTxtcantidadcompra() {
        return txtcantidadcompra;
    }

    public void setTxtcantidadcompra(JTextField txtcantidadcompra) {
        this.txtcantidadcompra = txtcantidadcompra;
    }

    public JTextField getTxtidfactura() {
        return txtidfactura;
    }

    public void setTxtidfactura(JTextField txtidfactura) {
        this.txtidfactura = txtidfactura;
    }

    public JTextField getTxtnomproduc() {
        return txtnomproduc;
    }

    public void setTxtnomproduc(JTextField txtnomproduc) {
        this.txtnomproduc = txtnomproduc;
    }

    public JTextField getTxtpreciounita() {
        return txtpreciounita;
    }

    public void setTxtpreciounita(JTextField txtpreciounita) {
        this.txtpreciounita = txtpreciounita;
    }

    public JButton getBtnbuscarproduct() {
        return btnbuscarproduct;
    }

    public void setBtnbuscarproduct(JButton btnbuscarproduct) {
        this.btnbuscarproduct = btnbuscarproduct;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelAgregarProducto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTablaagragarproducto = new javax.swing.JTable();
        lblidfactura = new javax.swing.JLabel();
        lblidproducto = new javax.swing.JLabel();
        txtidfactura = new javax.swing.JTextField();
        txtnomproduc = new javax.swing.JTextField();
        lblcantidadcompra = new javax.swing.JLabel();
        txtcantidadcompra = new javax.swing.JTextField();
        lblpreciounitario = new javax.swing.JLabel();
        txtpreciounita = new javax.swing.JTextField();
        btnagregar = new javax.swing.JButton();
        btnbuscarproduct = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanelAgregarProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar Producto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 36), new java.awt.Color(0, 153, 153))); // NOI18N

        JTablaagragarproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(JTablaagragarproducto);

        lblidfactura.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblidfactura.setForeground(new java.awt.Color(0, 153, 153));
        lblidfactura.setText("N° Factura");

        lblidproducto.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblidproducto.setForeground(new java.awt.Color(0, 153, 153));
        lblidproducto.setText("Producto");

        txtidfactura.setEditable(false);
        txtidfactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        txtnomproduc.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        lblcantidadcompra.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblcantidadcompra.setForeground(new java.awt.Color(0, 153, 153));
        lblcantidadcompra.setText("Cantidad Comprada");

        txtcantidadcompra.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        lblpreciounitario.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblpreciounitario.setForeground(new java.awt.Color(0, 153, 153));
        lblpreciounitario.setText("Precio Unitario");

        txtpreciounita.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        btnagregar.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnagregar.setForeground(new java.awt.Color(0, 153, 153));
        btnagregar.setText("Agregar");

        btnbuscarproduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar1.png"))); // NOI18N

        javax.swing.GroupLayout JPanelAgregarProductoLayout = new javax.swing.GroupLayout(JPanelAgregarProducto);
        JPanelAgregarProducto.setLayout(JPanelAgregarProductoLayout);
        JPanelAgregarProductoLayout.setHorizontalGroup(
            JPanelAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelAgregarProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelAgregarProductoLayout.createSequentialGroup()
                        .addComponent(lblidfactura)
                        .addGap(18, 18, 18)
                        .addComponent(txtidfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPanelAgregarProductoLayout.createSequentialGroup()
                        .addComponent(lblidproducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtnomproduc, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JPanelAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanelAgregarProductoLayout.createSequentialGroup()
                                .addComponent(btnbuscarproduct)
                                .addGap(55, 55, 55)
                                .addComponent(lblcantidadcompra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcantidadcompra, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblpreciounitario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtpreciounita, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(JPanelAgregarProductoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnagregar))))))
        );
        JPanelAgregarProductoLayout.setVerticalGroup(
            JPanelAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelAgregarProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblidfactura)
                    .addComponent(txtidfactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(JPanelAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblidproducto)
                        .addComponent(txtnomproduc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblcantidadcompra)
                        .addComponent(txtcantidadcompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblpreciounitario)
                        .addComponent(txtpreciounita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnbuscarproduct, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(7, 7, 7)
                .addComponent(btnagregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelAgregarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelAgregarProducto;
    private javax.swing.JTable JTablaagragarproducto;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnbuscarproduct;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcantidadcompra;
    private javax.swing.JLabel lblidfactura;
    private javax.swing.JLabel lblidproducto;
    private javax.swing.JLabel lblpreciounitario;
    private javax.swing.JTextField txtcantidadcompra;
    private javax.swing.JTextField txtidfactura;
    private javax.swing.JTextField txtnomproduc;
    private javax.swing.JTextField txtpreciounita;
    // End of variables declaration//GEN-END:variables
}
