/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author SENA
 */
public class Mostrar_Detalle_Factura_Compra extends javax.swing.JFrame {

    /**
     * Creates new form Buscar_Detalle_Factura_Compra
     */
    public Mostrar_Detalle_Factura_Compra() {
        initComponents();
    }

    public JPanel getJPanelbucardetallefactura() {
        return JPanelbucardetallefactura;
    }

    public void setJPanelbucardetallefactura(JPanel JPanelbucardetallefactura) {
        this.JPanelbucardetallefactura = JPanelbucardetallefactura;
    }

    public JTable getJTablaMostrarDetalleFactura() {
        return JTablaMostrarDetalleFactura;
    }

    public void setJTablaMostrarDetalleFactura(JTable JTablaMostrarDetalleFactura) {
        this.JTablaMostrarDetalleFactura = JTablaMostrarDetalleFactura;
    }

    public JTextField getTxtbuscardetalle() {
        return txtbuscardetalle;
    }

    public void setTxtbuscardetalle(JTextField txtbuscardetalle) {
        this.txtbuscardetalle = txtbuscardetalle;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelbucardetallefactura = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTablaMostrarDetalleFactura = new javax.swing.JTable();
        txtbuscardetalle = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanelbucardetallefactura.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mostrar Detalle Factura", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 36), new java.awt.Color(0, 153, 153))); // NOI18N

        JTablaMostrarDetalleFactura.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        JTablaMostrarDetalleFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(JTablaMostrarDetalleFactura);

        txtbuscardetalle.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtbuscardetalle.setForeground(new java.awt.Color(204, 204, 204));
        txtbuscardetalle.setText("Buscar");

        javax.swing.GroupLayout JPanelbucardetallefacturaLayout = new javax.swing.GroupLayout(JPanelbucardetallefactura);
        JPanelbucardetallefactura.setLayout(JPanelbucardetallefacturaLayout);
        JPanelbucardetallefacturaLayout.setHorizontalGroup(
            JPanelbucardetallefacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelbucardetallefacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelbucardetallefacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelbucardetallefacturaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtbuscardetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        JPanelbucardetallefacturaLayout.setVerticalGroup(
            JPanelbucardetallefacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelbucardetallefacturaLayout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addComponent(txtbuscardetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelbucardetallefactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelbucardetallefactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelbucardetallefactura;
    private javax.swing.JTable JTablaMostrarDetalleFactura;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtbuscardetalle;
    // End of variables declaration//GEN-END:variables
}
