/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author SENA
 */
public class Nueva_Venta extends javax.swing.JFrame {

    /**
     * Creates new form Nueva_Venta
     */
    public Nueva_Venta() {
        initComponents();
    }

    public JButton getBtncancelarventa() {
        return btncancelarventa;
    }

    public void setBtncancelarventa(JButton btncancelarventa) {
        this.btncancelarventa = btncancelarventa;
    }

    public JButton getBtnguardarventa() {
        return btnguardarventa;
    }

    public void setBtnguardarventa(JButton btnguardarventa) {
        this.btnguardarventa = btnguardarventa;
    }

    public JComboBox<String> getCmbtipopagoventa() {
        return cmbtipopagoventa;
    }

    public void setCmbtipopagoventa(JComboBox<String> cmbtipopagoventa) {
        this.cmbtipopagoventa = cmbtipopagoventa;
    }

    public JTextField getTxtidenticliventa() {
        return txtidenticliventa;
    }

    public void setTxtidenticliventa(JTextField txtidenticliventa) {
        this.txtidenticliventa = txtidenticliventa;
    }

    public JTextField getTxtidentusuaventa() {
        return txtidentusuaventa;
    }

    public void setTxtidentusuaventa(JTextField txtidentusuaventa) {
        this.txtidentusuaventa = txtidentusuaventa;
    }

    public JButton getBtnbuscarcliente() {
        return btnbuscarcliente;
    }

    public void setBtnbuscarcliente(JButton btnbuscarcliente) {
        this.btnbuscarcliente = btnbuscarcliente;
    }

    public JButton getBtnbuscarusuarioventa() {
        return btnbuscarusuarioventa;
    }

    public void setBtnbuscarusuarioventa(JButton btnbuscarusuarioventa) {
        this.btnbuscarusuarioventa = btnbuscarusuarioventa;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelnuevaventa = new javax.swing.JPanel();
        lblidenticlienventa = new javax.swing.JLabel();
        lblidentiusuventa = new javax.swing.JLabel();
        lbltipopagoventa = new javax.swing.JLabel();
        btnguardarventa = new javax.swing.JButton();
        btncancelarventa = new javax.swing.JButton();
        txtidenticliventa = new javax.swing.JTextField();
        txtidentusuaventa = new javax.swing.JTextField();
        cmbtipopagoventa = new javax.swing.JComboBox<>();
        btnbuscarcliente = new javax.swing.JButton();
        btnbuscarusuarioventa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelnuevaventa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nueva Venta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 36), new java.awt.Color(0, 153, 153))); // NOI18N

        lblidenticlienventa.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblidenticlienventa.setForeground(new java.awt.Color(0, 153, 153));
        lblidenticlienventa.setText("Identificación Cliente");

        lblidentiusuventa.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblidentiusuventa.setForeground(new java.awt.Color(0, 153, 153));
        lblidentiusuventa.setText("Identificación Usuario");

        lbltipopagoventa.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lbltipopagoventa.setForeground(new java.awt.Color(0, 153, 153));
        lbltipopagoventa.setText("Tipo de Pago");

        btnguardarventa.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnguardarventa.setForeground(new java.awt.Color(0, 153, 153));
        btnguardarventa.setText("Guardar");

        btncancelarventa.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btncancelarventa.setForeground(new java.awt.Color(0, 153, 153));
        btncancelarventa.setText("Cancelar");

        txtidenticliventa.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        txtidentusuaventa.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        cmbtipopagoventa.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmbtipopagoventa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "PSE", "Tarjete de Débito", "Tarjeta de Crédito", "Efectivo" }));

        btnbuscarcliente.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnbuscarcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar1.png"))); // NOI18N

        btnbuscarusuarioventa.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnbuscarusuarioventa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar1.png"))); // NOI18N

        javax.swing.GroupLayout panelnuevaventaLayout = new javax.swing.GroupLayout(panelnuevaventa);
        panelnuevaventa.setLayout(panelnuevaventaLayout);
        panelnuevaventaLayout.setHorizontalGroup(
            panelnuevaventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelnuevaventaLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(btnguardarventa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelnuevaventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbtipopagoventa, 0, 244, Short.MAX_VALUE)
                    .addComponent(txtidentusuaventa)
                    .addComponent(txtidenticliventa)
                    .addGroup(panelnuevaventaLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btncancelarventa)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelnuevaventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbuscarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscarusuarioventa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(panelnuevaventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelnuevaventaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelnuevaventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblidenticlienventa, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblidentiusuventa, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbltipopagoventa, javax.swing.GroupLayout.Alignment.LEADING))
                    .addContainerGap(339, Short.MAX_VALUE)))
        );
        panelnuevaventaLayout.setVerticalGroup(
            panelnuevaventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelnuevaventaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelnuevaventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtidenticliventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscarcliente))
                .addGap(18, 18, 18)
                .addGroup(panelnuevaventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtidentusuaventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscarusuarioventa))
                .addGap(18, 18, 18)
                .addComponent(cmbtipopagoventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(panelnuevaventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardarventa)
                    .addComponent(btncancelarventa))
                .addGap(34, 34, 34))
            .addGroup(panelnuevaventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelnuevaventaLayout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(lblidenticlienventa)
                    .addGap(18, 18, 18)
                    .addComponent(lblidentiusuventa)
                    .addGap(18, 18, 18)
                    .addComponent(lbltipopagoventa)
                    .addContainerGap(102, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelnuevaventa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelnuevaventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscarcliente;
    private javax.swing.JButton btnbuscarusuarioventa;
    private javax.swing.JButton btncancelarventa;
    private javax.swing.JButton btnguardarventa;
    private javax.swing.JComboBox<String> cmbtipopagoventa;
    private javax.swing.JLabel lblidenticlienventa;
    private javax.swing.JLabel lblidentiusuventa;
    private javax.swing.JLabel lbltipopagoventa;
    private javax.swing.JPanel panelnuevaventa;
    private javax.swing.JTextField txtidenticliventa;
    private javax.swing.JTextField txtidentusuaventa;
    // End of variables declaration//GEN-END:variables
}
