/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author SENA
 */
public class Nueva_Venta extends javax.swing.JFrame {

    /**
     * Creates new form Nueva_Venta
     */
    public Nueva_Venta() {
        initComponents();
    }

    public JButton getBtncancelarventa() {
        return btncancelarventa;
    }

    public void setBtncancelarventa(JButton btncancelarventa) {
        this.btncancelarventa = btncancelarventa;
    }

    public JButton getBtnguardarventa() {
        return btnguardarventa;
    }

    public void setBtnguardarventa(JButton btnguardarventa) {
        this.btnguardarventa = btnguardarventa;
    }

    public JComboBox<String> getCmbtipopagoventa() {
        return cmbtipopagoventa;
    }

    public void setCmbtipopagoventa(JComboBox<String> cmbtipopagoventa) {
        this.cmbtipopagoventa = cmbtipopagoventa;
    }

    public JPanel getPanelnuevaventa() {
        return panelnuevaventa;
    }

    public void setPanelnuevaventa(JPanel panelnuevaventa) {
        this.panelnuevaventa = panelnuevaventa;
    }

    public JTextField getTxtidentiprovefact() {
        return txtidentiprovefact;
    }

    public void setTxtidentiprovefact(JTextField txtidentiprovefact) {
        this.txtidentiprovefact = txtidentiprovefact;
    }

    public JTextField getTxtidentiusufactcomp() {
        return txtidentiusufactcomp;
    }

    public void setTxtidentiusufactcomp(JTextField txtidentiusufactcomp) {
        this.txtidentiusufactcomp = txtidentiusufactcomp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelnuevaventa = new javax.swing.JPanel();
        lblidenticlienventa = new javax.swing.JLabel();
        txtidentiprovefact = new javax.swing.JTextField();
        lblidentiusuventa = new javax.swing.JLabel();
        txtidentiusufactcomp = new javax.swing.JTextField();
        lbltipopagoventa = new javax.swing.JLabel();
        cmbtipopagoventa = new javax.swing.JComboBox<>();
        btnguardarventa = new javax.swing.JButton();
        btncancelarventa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelnuevaventa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nueva Venta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 36), new java.awt.Color(0, 153, 153))); // NOI18N

        lblidenticlienventa.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblidenticlienventa.setForeground(new java.awt.Color(0, 153, 153));
        lblidenticlienventa.setText("Identificación Cliente");

        txtidentiprovefact.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        lblidentiusuventa.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblidentiusuventa.setForeground(new java.awt.Color(0, 153, 153));
        lblidentiusuventa.setText("Identificación Usuario");

        txtidentiusufactcomp.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        lbltipopagoventa.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lbltipopagoventa.setForeground(new java.awt.Color(0, 153, 153));
        lbltipopagoventa.setText("Tipo de Pago");

        cmbtipopagoventa.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmbtipopagoventa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "PSE", "Tarjeta de Débito", "Tarjeta de Crédito", "Efectivo" }));

        btnguardarventa.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnguardarventa.setForeground(new java.awt.Color(0, 153, 153));
        btnguardarventa.setText("Guardar");

        btncancelarventa.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btncancelarventa.setForeground(new java.awt.Color(0, 153, 153));
        btncancelarventa.setText("Cancelar");

        javax.swing.GroupLayout panelnuevaventaLayout = new javax.swing.GroupLayout(panelnuevaventa);
        panelnuevaventa.setLayout(panelnuevaventaLayout);
        panelnuevaventaLayout.setHorizontalGroup(
            panelnuevaventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelnuevaventaLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnguardarventa)
                .addGap(37, 37, 37)
                .addComponent(btncancelarventa)
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(panelnuevaventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelnuevaventaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelnuevaventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelnuevaventaLayout.createSequentialGroup()
                            .addGroup(panelnuevaventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblidenticlienventa)
                                .addComponent(lblidentiusuventa))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelnuevaventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtidentiusufactcomp, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                .addComponent(txtidentiprovefact)))
                        .addGroup(panelnuevaventaLayout.createSequentialGroup()
                            .addComponent(lbltipopagoventa)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                            .addComponent(cmbtipopagoventa, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        panelnuevaventaLayout.setVerticalGroup(
            panelnuevaventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelnuevaventaLayout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addGroup(panelnuevaventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardarventa)
                    .addComponent(btncancelarventa))
                .addGap(34, 34, 34))
            .addGroup(panelnuevaventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelnuevaventaLayout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addGroup(panelnuevaventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblidenticlienventa)
                        .addComponent(txtidentiprovefact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(panelnuevaventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblidentiusuventa)
                        .addComponent(txtidentiusufactcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(panelnuevaventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbltipopagoventa)
                        .addComponent(cmbtipopagoventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(101, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelnuevaventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelnuevaventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelarventa;
    private javax.swing.JButton btnguardarventa;
    private javax.swing.JComboBox<String> cmbtipopagoventa;
    private javax.swing.JLabel lblidenticlienventa;
    private javax.swing.JLabel lblidentiusuventa;
    private javax.swing.JLabel lbltipopagoventa;
    private javax.swing.JPanel panelnuevaventa;
    private javax.swing.JTextField txtidentiprovefact;
    private javax.swing.JTextField txtidentiusufactcomp;
    // End of variables declaration//GEN-END:variables
}
