/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;

/**
 *
 * @author SENA
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Principal() {
        initComponents();
    }

    public JButton getBtnnuevo() {
        return btnnuevo;
    }

    public void setBtnnuevo(JButton btnnuevo) {
        this.btnnuevo = btnnuevo;
    }

    public JButton getBtnnueclien() {
        return btnnueclien;
    }

    public void setBtnnueclien(JButton btnnueclien) {
        this.btnnueclien = btnnueclien;
    }

    public JButton getBtnnuevoprovee() {
        return btnnuevoprovee;
    }

    public void setBtnnuevoprovee(JButton btnnuevoprovee) {
        this.btnnuevoprovee = btnnuevoprovee;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbltienda = new javax.swing.JLabel();
        tpPrincipal = new javax.swing.JTabbedPane();
        jpusuario = new javax.swing.JPanel();
        btnnuevo = new javax.swing.JButton();
        jpcliente = new javax.swing.JPanel();
        btnnueclien = new javax.swing.JButton();
        jpproveedor = new javax.swing.JPanel();
        btnnuevoprovee = new javax.swing.JButton();
        jpproducto = new javax.swing.JPanel();
        jpfactura = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltienda.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        lbltienda.setForeground(new java.awt.Color(204, 0, 204));
        lbltienda.setText("TIENDA.COM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(lbltienda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lbltienda)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        tpPrincipal.setForeground(new java.awt.Color(204, 0, 204));
        tpPrincipal.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N

        btnnuevo.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnnuevo.setForeground(new java.awt.Color(204, 0, 204));
        btnnuevo.setIcon(new javax.swing.ImageIcon("C:\\Users\\SENA\\Documents\\NetBeansProjects\\Tienda_Com\\src\\main\\resources\\img\\usuario.png")); // NOI18N
        btnnuevo.setText("Nuevo");
        btnnuevo.setBorder(null);

        javax.swing.GroupLayout jpusuarioLayout = new javax.swing.GroupLayout(jpusuario);
        jpusuario.setLayout(jpusuarioLayout);
        jpusuarioLayout.setHorizontalGroup(
            jpusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpusuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(634, Short.MAX_VALUE))
        );
        jpusuarioLayout.setVerticalGroup(
            jpusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpusuarioLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        tpPrincipal.addTab("Usuario", jpusuario);

        btnnueclien.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnnueclien.setForeground(new java.awt.Color(204, 0, 204));
        btnnueclien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        btnnueclien.setText("Nuevo");

        javax.swing.GroupLayout jpclienteLayout = new javax.swing.GroupLayout(jpcliente);
        jpcliente.setLayout(jpclienteLayout);
        jpclienteLayout.setHorizontalGroup(
            jpclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpclienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnnueclien)
                .addContainerGap(618, Short.MAX_VALUE))
        );
        jpclienteLayout.setVerticalGroup(
            jpclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpclienteLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnnueclien)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        tpPrincipal.addTab("Cliente", jpcliente);

        btnnuevoprovee.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnnuevoprovee.setForeground(new java.awt.Color(204, 0, 204));
        btnnuevoprovee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        btnnuevoprovee.setText("Nuevo");

        javax.swing.GroupLayout jpproveedorLayout = new javax.swing.GroupLayout(jpproveedor);
        jpproveedor.setLayout(jpproveedorLayout);
        jpproveedorLayout.setHorizontalGroup(
            jpproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpproveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnnuevoprovee)
                .addContainerGap(618, Short.MAX_VALUE))
        );
        jpproveedorLayout.setVerticalGroup(
            jpproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpproveedorLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnnuevoprovee)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        tpPrincipal.addTab("Proveedor", jpproveedor);

        javax.swing.GroupLayout jpproductoLayout = new javax.swing.GroupLayout(jpproducto);
        jpproducto.setLayout(jpproductoLayout);
        jpproductoLayout.setHorizontalGroup(
            jpproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
        );
        jpproductoLayout.setVerticalGroup(
            jpproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );

        tpPrincipal.addTab("Producto", jpproducto);

        javax.swing.GroupLayout jpfacturaLayout = new javax.swing.GroupLayout(jpfactura);
        jpfactura.setLayout(jpfacturaLayout);
        jpfacturaLayout.setHorizontalGroup(
            jpfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
        );
        jpfacturaLayout.setVerticalGroup(
            jpfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );

        tpPrincipal.addTab("Factura", jpfactura);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnnueclien;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnnuevoprovee;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpcliente;
    private javax.swing.JPanel jpfactura;
    private javax.swing.JPanel jpproducto;
    private javax.swing.JPanel jpproveedor;
    private javax.swing.JPanel jpusuario;
    private javax.swing.JLabel lbltienda;
    private javax.swing.JTabbedPane tpPrincipal;
    // End of variables declaration//GEN-END:variables
}
